"""Public portfolio catalog and individual work pages."""
from flask import Blueprint, abort, render_template

portfolio_bp = Blueprint('portfolio', __name__)

WORKS = [
    dict(slug='running-diary-03', category='video', label='VIDEO · RUNNING 03', status='자체 프로젝트',
         image='showcase/running-video/episode-03-poster.jpg', video='showcase/running-video/episode-03.mp4',
         orientation='portrait', project='순금이의 러닝일지', title='1분 뛰고 90초 걷기, 타이머에 맡겨요.',
         description='실제 웹 타이머에 운동 순서를 입력하고, 저장과 전환 알림까지 확인하는 3편입니다.',
         format='세로 영상 · 2분 4초 · 음악 포함',
         overview='2편에서 소개한 NHS Couch to 5K 첫날 순서를 Online Interval Timer 웹사이트에 설정합니다. 준비 걷기 300초, 달리기 60초와 걷기 90초를 7회 반복한 뒤 마지막 달리기 60초, 마무리 걷기 300초를 넣는 과정을 보여줍니다. 자신의 몸에 맞는 속도로 하고 이상이 느껴지면 멈추세요.',
         approach='순금이의 인사와 짧은 상황 연출에 실제 웹사이트 조작 녹화를 연결했습니다. PC Chrome에서 모바일 화면 크기로 녹화했으며, 설정 화면은 속도를 조절하고 알림 전환의 대기 구간은 생략했습니다. 실물 휴대폰의 잠금·백그라운드 알림은 검증하지 않았으므로 화면을 켜고 자신의 기기에서 먼저 시험해 주세요. 캐릭터와 음성은 AI 제작, 배경음악은 자체 제작입니다.'),
    dict(slug='running-diary-02', category='video', label='VIDEO · RUNNING 02', status='자체 프로젝트',
         image='showcase/running-video/episode-02-poster.jpg', video='showcase/running-video/episode-02.mp4',
         orientation='portrait', project='순금이의 러닝일지', title='뛰다가 걸어도 돼요! 초보 러닝 첫날 순서.',
         description='걷기도 계획의 일부예요. 준비 걷기부터 마무리까지, 첫날의 운동 순서를 알아봅니다.',
         format='세로 영상 · 1분 18초 · 음악 포함',
         overview='NHS Couch to 5K 첫날 계획을 예시로 준비 걷기 5분, 달리기 1분과 걷기 90초를 7회 반복, 마지막 달리기 1분, 마무리 걷기 5분을 설명합니다. 스트레칭 제외 총 28분 30초이며 달리기는 8분입니다. 모든 사람에게 같은 운동량을 권하는 규칙은 아니며 자신의 몸에 맞는 속도로 하고 이상이 느껴지면 멈추세요.',
         approach='같은 여성 순금이 진행자와 움직이는 순서·시간 그래픽으로 설명합니다. 다른 체형의 러너 자료는 사용하지 않았습니다. 캐릭터와 목소리는 AI로 제작했으며 자체 제작 배경음악을 더했습니다. 다음 3편에서 실제 타이머 설정으로 이어집니다.'),
    dict(slug='running-diary-short-01', category='video', label='VIDEO · RUNNING SHORTS', status='자체 프로젝트',
         image='showcase/running-video/poster.jpg', video='showcase/running-video/running-short-music.mp4',
         orientation='portrait', project='순금이의 러닝일지', title='내 러닝 속도, 이 정도면 괜찮을까?',
         description='대화 테스트로 러닝 강도를 살펴보는, 순금이의 43초 러닝 쇼츠입니다.',
         format='세로 쇼츠 · 약 43초 · 음악 포함',
         overview='달릴 때 자신의 운동 강도를 확인하는 대화 테스트를 소개한 러닝 콘텐츠입니다. CDC의 신체 활동 강도 측정 안내를 바탕으로 구성했으며, 영상 장면과 순금이의 목소리는 AI로 제작했습니다.',
         approach='짧은 인사와 질문으로 시작하고, 달리는 장면과 큰 한글 자막으로 내용을 전합니다. 순금이의 내레이션에 자체 제작 배경음악 Sunny Steps를 더한 최종본입니다.'),
    dict(slug='sotttukkeong-sns-concept', category='social', label='SNS · FOOD CONCEPT', status='자체 콘셉트',
         image='showcase/sotttukkeong-sns-concept.png', project='순금이 AI 작업실 · 자체 콘셉트',
         title='솥뚜껑 삼겹살 SNS · 오늘 모임, 솥뚜껑 앞으로.',
         description='노릇하게 구운 삼겹살과 무쇠 솥뚜껑으로 함께 모이는 저녁을 담았습니다.',
         format='SNS 홍보 이미지 · 1080×1350',
         overview='솥뚜껑 삼겹살집을 주제로 우리 홈페이지 SNS 기능에서 만든 홍보 시안입니다. 특정 매장의 의뢰가 아닌 자체 콘셉트로, 상호 대신 업종 이름을 사용했습니다. 음식과 공간은 실제 매장 사진이 아닌 AI 생성 이미지입니다.',
         approach='어두운 식탁 위 무쇠 솥뚜껑과 삼겹살의 구운 질감을 크게 보여주고, 흰 제목을 사진 위에 배치했습니다. 함께 둘러앉아 고기를 굽고 이야기를 나누는 상황에서 문구를 시작했습니다.',
         caption='오늘 모임, 솥뚜껑 앞으로.\n\n솥뚜껑 삼겹살\n\n지글지글 익는 소리 들으면서\n앞사람 이야기 하나 더 듣게 되는 자리.\n\n고기 굽는 손길 사이로\n웃음도 대화도 조금씩 더 무르익는\n그 저녁의 분위기를 담았습니다. 🔥\n\n홍보 시안 · AI 이미지\n\n실제 매장 사진이 아닌 AI 홍보 시안입니다.\n\n#솥뚜껑삼겹살 #삼겹살 #솥뚜껑삼겹살집 #고기모임 #저녁모임 #인스타홍보 #외식무드 #고기굽는시간 #AI홍보시안'),
    dict(slug='lotteria-sns-concept', category='social', label='SNS · FOOD CONCEPT', status='비공식 콘셉트',
         image='showcase/lotteria-sns-concept.png', project='순금이 AI 작업실 · 자체 콘셉트',
         title='롯데리아 SNS · 점심 고민, 여기까지.',
         description='점심 메뉴를 고르는 순간을 짧은 문구와 따뜻한 음식 이미지로 담았습니다.',
         format='SNS 홍보 이미지 · 1080×1350',
         overview='롯데리아를 주제로 우리 홈페이지 SNS 기능에서 만든 자체 디자인입니다. 공식 광고나 의뢰·협업이 아니며, 음식은 실제 판매 메뉴 사진이 아닌 AI 생성 이미지입니다.',
         approach='크림색 바탕과 검정 제목, 빨강 포인트로 구성했습니다. 막연한 즐거움을 이야기하는 대신 점심 메뉴를 고르는 상황에서 문구를 시작하고, 제목과 사진을 분리해 읽기 쉽게 정리했습니다. 홈페이지에서 생성한 최종 원본을 그대로 공개합니다.',
         caption='12시 넘어서도 못 고르면, 이제 끝.\n\n롯데리아 · 비공식 콘셉트\n\n뭘 먹을지 넘기기만 하던 점심시간,\n멈출 이유는 하나면 됩니다.\n\n점심 고민, 여기까지.\n\n비공식 콘셉트·AI 이미지이며 공식 광고나 협업이 아닙니다.\n\n#롯데리아 #롯데리아비공식콘셉트 #버거무드 #점심메뉴 #점심시간 #메뉴고민 #인스타브랜드콘셉트 #푸드콘텐츠 #버거콘텐츠',
         gallery_title='맥도날드와 롯데리아, 두 가지 표현',
         gallery_note='서로 다른 제작 방향으로 만든 비공식 콘셉트입니다. 이미지를 누르면 원본 크기로 볼 수 있습니다.',
         gallery=[
             dict(image='showcase/mcdonalds-sns-concept.png', title='맥도날드 · 한 입의 즐거움', description='짙은 빨강과 흰 제목으로 즐거움을 강조한 기존 시안입니다.'),
             dict(image='showcase/lotteria-sns-concept.png', title='롯데리아 · 점심 고민, 여기까지.', description='밝은 크림색과 짧은 제목으로 점심 메뉴를 고르는 순간을 담았습니다.'),
         ]),
    dict(slug='ai-experiment-short', category='video', label='VIDEO · SHORTS', status='자체 프로젝트',
         image='showcase/ai-experiment-video/short-poster.jpg', video='showcase/ai-experiment-video/short-music.mp4',
         orientation='portrait', project='순금이의 AI 실험실', title='22초로 보는, 첫 AI 수익 실험.',
         description='AI 이미지 제출부터 심사 결과까지, 짧고 경쾌하게 담은 쇼츠입니다.',
         format='세로 쇼츠 · 22초 · 음악 포함',
         overview='Adobe Stock에 AI 이미지를 제출한 실험을 실제 이미지와 당시 심사·수익 기록으로 소개합니다. 작업 장면 일부는 AI로 연출했으며, 순금이의 AI 내레이션과 자막으로 이야기를 전합니다.',
         approach='밝고 친근한 목소리에 자체 제작 배경음악 Sunny Steps를 더했습니다. 말할 때는 음악을 낮추고, 마지막에는 다음 실험에 대한 질문을 남겼습니다.'),
    dict(slug='ai-experiment-episode-01', category='video', label='VIDEO · EPISODE 01', status='자체 프로젝트',
         image='showcase/ai-experiment-video/episode-poster.jpg', video='showcase/ai-experiment-video/episode-01-music.mp4',
         orientation='landscape', project='순금이의 AI 실험실', title='AI 이미지, 첫 실험의 기록.',
         description='어떤 사진이 승인됐을까요? 제출한 이미지와 결과를 함께 살펴보는 첫 본편입니다.',
         format='가로 영상 · 약 4분 6초 · 음악 포함',
         overview='순금이의 AI 실험실 첫 번째 본편입니다. 제출한 사진 중 승인된 이미지를 함께 골라보고, 당시 심사 분류와 수익 기록, 다음에 수정할 사진으로 이야기를 이어갑니다. 실제 기록과 AI 연출 장면을 구분했습니다.',
         approach='사진과 기록 화면, AI 내레이션, 자막으로 실험 과정을 설명합니다. 밝고 가벼운 자체 제작 음악 Sunny Steps를 더하고, 목소리가 잘 들리도록 발화 중 배경음악을 낮췄습니다.'),
    dict(slug='burger-sns-four-directions', category='social', label='SNS · ART DIRECTION', status='디자인 스터디',
         image='showcase/burger-directions/overview.png', project='순금이 AI 작업실 · 자체 콘셉트',
         title='같은 사진, 네 가지 시선.',
         description='한 장의 버거 사진을 네 가지 구도로 풀어낸 SNS 디자인 시리즈입니다.',
         format='SNS 디자인 시리즈 · 4종',
         overview='같은 사진과 문구도 무엇을 강조하느냐에 따라 인상이 달라집니다. 사진의 빈 공간, 제품의 크기, 제목의 비중, 좌우 배치를 바꾸어 네 가지 방향을 만들었습니다. 음식은 실제 판매 메뉴 사진이 아닌 비교용 AI 생성 이미지입니다.',
         approach='빨강과 크림색, 짧은 제목을 공통으로 두고 사진과 문구의 관계를 달리했습니다. 별도로 생성한 AI 사진에 작업실의 새 문구 배치 방식을 적용한 자체 디자인 스터디입니다.',
         gallery=[
             dict(image='showcase/burger-directions/full_bleed_photo.png', title='01 · 사진의 빈 공간', description='사진을 가득 채우고 조용한 공간에 제목을 놓았습니다.'),
             dict(image='showcase/burger-directions/product_closeup.png', title='02 · 제품 중심', description='버거를 크게 보여주고 문구는 상단에 정리했습니다.'),
             dict(image='showcase/burger-directions/editorial_type.png', title='03 · 큰 글자 중심', description='제목이 먼저 읽히도록 글자와 사진의 비중을 조절했습니다.'),
             dict(image='showcase/burger-directions/split_scene.png', title='04 · 좌우 분할', description='문구와 사진을 나란히 두어 서로의 영역을 확보했습니다.'),
         ]),
    dict(slug='mcdonalds-sns-concept', category='social', label='SNS · FOOD CONCEPT', status='비공식 콘셉트',
         image='showcase/mcdonalds-sns-concept.png', project='순금이 AI 작업실 · 자체 콘셉트',
         title='맥도날드 SNS · 한 입의 즐거움.',
         description='우리 홈페이지 SNS 기능으로 만든, 빨강 배경과 버거 중심의 비공식 콘셉트 홍보물입니다.',
         format='SNS 홍보 이미지 · 1080×1350',
         overview='맥도날드를 주제로 순금이 AI 작업실의 제작 스타일을 보여주는 자체 프로젝트입니다. 홈페이지 SNS 기능에 업종과 제작 브리프, 이미지 스타일을 입력해 문구와 이미지를 생성했습니다. 공식 의뢰·협업·캠페인이 아니며, 음식은 실제 판매 메뉴 사진이 아닌 AI 생성 이미지입니다.',
         approach='구도·색감·빛·음식 질감·타이포그래피 기준을 조합했습니다. 짙은 빨강 배경과 크게 배치한 버거, 짧은 흰색 제목을 중심으로 구성했습니다. 첫 결과의 글자 중복을 확인한 뒤, 글자 없는 사진층과 한글 조판을 분리하도록 입력을 수정했습니다. 최종 결과는 홈페이지에서 생성한 원본 그대로 공개합니다.',
         caption='맥도날드, 한 입에 번지는 가장 선명한 즐거움 🍔\n부드러운 참깨빵과 진한 패티, 녹아드는 치즈의 조화가 보는 순간부터 식욕을 깨워요.\n한 컷만으로도 버거의 맛있는 존재감을 또렷하게 전하는 인스타그램 콘셉트입니다.\n한 입의 즐거움을 담은 버거 무드가 필요하다면 맥도날드 관련 콘셉트도 함께 이야기해보세요.\n※ 본 캡션은 순금이 AI 작업실의 비공식 콘셉트이며 공식 의뢰·협업이 아닙니다.\n#맥도날드 #버거사진 #푸드스타일링 #푸드콘텐츠 #인스타감성 #버거콘셉트 #음식사진 #SNS콘텐츠 #한입의즐거움'),
    dict(slug='running-form-report', category='report', label='REPORT · RUNNING COACH', status='디자인 샘플',
         image='showcase/sungeum-running-report-studio.png',
         title='달리기를 한눈에, 러닝폼 리포트.',
         description='점수와 자세, 다음 러닝의 포인트를 한 장에 정리한 리포트 디자인입니다.',
         format='러닝 분석 리포트 · PNG',
         overview='순금이 러닝코치의 저장·공유 리포트를 작업실 홈페이지와 같은 스타일로 제작했습니다. 이 작업물의 점수와 각도는 디자인을 보여주기 위한 예시이며, 실제 이용자의 영상 분석 결과가 아닙니다. 분석 장면 역시 직접 그린 예시 일러스트입니다.',
         approach='흰 배경과 검정 글자, 청보라 강조색을 사용했습니다. 종합 점수, 자세 시각화와 착지 확대, 핵심 수치, 코칭 한마디를 차례로 배치했습니다. 실제 서비스에서는 이용자의 분석 장면과 결과가 들어가며, 같은 이미지를 다운로드하고 생성 기록에 저장합니다.'),
    dict(slug='7days-massage-sns', category='social', label='SNS · LOCAL BUSINESS', status='실제 게시',
         image='showcase/7days-massage-pattaya-sns.png', project="7day’s massage",
         title='7day’s massage · SNS 홍보',
         description='파타야 마사지샵을 위해 만든, 편안한 휴식 분위기의 SNS 홍보 이미지입니다.',
         format='SNS 홍보 이미지',
         overview='7day’s massage의 인스타그램 홍보를 위해 제작한 작업물입니다. 여행과 쇼핑 중 잠시 쉬어가는 장면을 AI 이미지로 표현했습니다.',
         approach='따뜻한 나무색과 자연광, 초록 식물을 활용해 편안한 분위기를 구성했습니다. 매장 이름이 먼저 읽히도록 중앙에 배치했습니다.',
         caption='파타야 터미널21에서 많이 걷고 난 뒤,\n잠시 편안하게 쉬어가세요. 🌿\n\n쇼핑과 관광으로 쌓인 피로를 가볍게 풀고 나면\n남은 여행 일정도 한층 여유로워집니다.'),
    dict(slug='conversion-ad', category='social', label='AD · VISUAL DIRECTION', status='자체 프로젝트',
         image='showcase/project-freedom-conversion-ad-v1.png',
         title='눈길에서, 다음 행동으로.',
         description='선명한 색과 큰 제목으로 콘텐츠 제작 기능을 소개하는 광고 디자인입니다.',
         format='디지털 광고 이미지',
         overview='한 번의 입력으로 여러 종류의 홍보물을 만들 수 있다는 메시지를 담았습니다. SNS, 광고, 블로그, 포스터 예시를 한 화면에 보여줍니다.',
         approach='파랑과 노랑의 대비로 주요 메시지를 강조하고, 하단에 제작 예시를 나란히 배치했습니다.'),
    dict(slug='brand-poster', category='brand', label='BRAND · POSTER', status='자체 프로젝트',
         image='showcase/project-freedom-poster-v4.png',
         title='한눈에 읽히는, 브랜드의 목소리.',
         description='검정과 빨강, 큰 글자로 정리한 Project Freedom AI의 브랜드 홍보 포스터입니다.',
         format='브랜드 포스터',
         overview='여러 홍보물 제작 기능을 한곳에서 이용할 수 있다는 메시지를 전달하는 브랜드 포스터입니다.',
         approach='어두운 바탕 위에 큰 제목을 배치하고, 네 가지 제작 분야를 구분했습니다. 빨간 면과 흰 글자로 읽는 순서를 만들었습니다.'),
    dict(slug='ai-studio-website', category='web', label='WEB · UI', status='자체 프로젝트',
         image='showcase/ai-studio-homepage-v4.png',
         title='작업물이 먼저 보이는 홈페이지.',
         description='실제 결과물과 AI 도구를 둘러볼 수 있도록 구성한 순금이의 AI 작업실입니다.',
         format='반응형 홈페이지',
         overview='어떤 콘텐츠를 만드는 곳인지 첫 화면에서 알 수 있도록 작업물을 앞에 배치한 홈페이지 시안입니다.',
         approach='흰 배경과 검정 글자를 중심으로 작업물, 제작 과정, AI 도구를 구분했습니다. 데스크톱과 모바일 크기에 맞춰 카드 배열을 조정했습니다.'),
]


@portfolio_bp.get('/works/<slug>')
def detail(slug):
    work = next((item for item in WORKS if item['slug'] == slug), None)
    if work is None:
        abort(404)
    return render_template('work_detail.html', work=work,
                           related=[item for item in WORKS if item['slug'] != slug])
