RUNNING_COACH_COPY = {
    "ko": {
        "eyebrow":"순금이 러닝코치", "title":"오늘 러닝, 순금이랑 정해볼까?", "desc":"영상 없이도 지금 컨디션에 맞는 러닝 계획을 무료로 만들어줄게.",
        "condition":"오늘 몸 상태는 어때?", "good":"좋아, 가볍게 달리고 싶어", "normal":"보통이야", "tired":"조금 피곤해", "pain":"통증이 있어",
        "minutes":"오늘 몇 분 정도 뛸 수 있어?", "goal":"오늘 러닝의 목적은 뭐야?", "easy":"가볍게 뛰기", "fitness":"체력 키우기", "weight":"체중 관리", "race":"대회 준비", "submit":"순금이에게 무료 코칭 받기", "thinking":"순금이가 오늘 계획을 정리하고 있어…", "error":"코칭을 만들지 못했어요.",
        "plan":"오늘의 계획", "intensity":"추천 강도", "warmup":"워밍업", "caution":"주의사항", "cooldown":"마무리", "feedback_title":"순금이 러닝코치는 어땠어? 🐶", "feedback_prompt":"다음 러닝 계획을 더 잘 만들 수 있게 한 번만 알려줘.", "helpful":"👍 도움이 됐어", "neutral":"🙂 보통이야", "not_helpful":"🤔 아쉬워", "feedback_placeholder":"짧은 후기를 남겨줘 (선택)", "feedback_send":"후기 보내기", "thanks":"고마워! 다음 러닝도 더 잘 도와줄게 🐶✨", "fallback":"기본 안전 코칭으로 안내했어.", "ai":"순금이가 너에게 맞춰 정리했어."
    },
    "en": {
        "eyebrow":"Sungeum Running Coach", "title":"Shall we plan today's run together?", "desc":"Get a free running plan tailored to how you feel today, even without a video.", "condition":"How are you feeling today?", "good":"Good, I want an easy run", "normal":"I feel normal", "tired":"I'm a little tired", "pain":"I have pain", "minutes":"How many minutes can you run today?", "goal":"What is today's running goal?", "easy":"Easy jog", "fitness":"Build stamina", "weight":"Manage weight", "race":"Prepare for a race", "submit":"Get free coaching from Sungeum", "thinking":"Sungeum is preparing today's plan…", "error":"We couldn't create the coaching plan.", "plan":"Today's plan", "intensity":"Recommended intensity", "warmup":"Warm-up", "caution":"Cautions", "cooldown":"Cool-down", "feedback_title":"How was Sungeum's running coach? 🐶", "feedback_prompt":"Tell me once so I can make your next plan better.", "helpful":"👍 Helpful", "neutral":"🙂 It was okay", "not_helpful":"🤔 Needs work", "feedback_placeholder":"Leave a short note (optional)", "feedback_send":"Send feedback", "thanks":"Thanks! I'll help even better next run 🐶✨", "fallback":"I used the safe default coaching plan.", "ai":"Sungeum tailored this plan for you."
    },
    "ja": {
        "eyebrow":"スングム ランニングコーチ", "title":"今日のランニングを一緒に決めようか？", "desc":"動画がなくても、今日の体調に合うプランを無料で作ります。", "condition":"今日の体調はどう？", "good":"元気、軽く走りたい", "normal":"普通です", "tired":"少し疲れています", "pain":"痛みがあります", "minutes":"今日は何分走れそう？", "goal":"今日の目標は？", "easy":"軽く走る", "fitness":"体力づくり", "weight":"体重管理", "race":"大会準備", "submit":"無料コーチングを受ける", "thinking":"今日のプランを整理中…", "error":"コーチングを作成できませんでした。", "plan":"今日のプラン", "intensity":"おすすめ強度", "warmup":"ウォームアップ", "caution":"注意点", "cooldown":"クールダウン", "feedback_title":"スングムのランニングコーチはどうだった？ 🐶", "feedback_prompt":"次のプランを良くするために教えてね。", "helpful":"👍 役に立った", "neutral":"🙂 ふつう", "not_helpful":"🤔 改善が必要", "feedback_placeholder":"短い感想（任意）", "feedback_send":"感想を送る", "thanks":"ありがとう！次ももっと上手に手伝うね 🐶✨", "fallback":"安全な基本プランで案内しました。", "ai":"あなたに合わせて整理しました。"
    },
    "th": {
        "eyebrow":"โค้ชวิ่งซุนกึม", "title":"มาวางแผนวิ่งวันนี้กับซุนกึมกันไหม?", "desc":"รับแผนวิ่งฟรีที่เหมาะกับสภาพร่างกายวันนี้ แม้ไม่มีวิดีโอ", "condition":"วันนี้รู้สึกอย่างไรบ้าง?", "good":"ดี อยากวิ่งเบา ๆ", "normal":"ปกติดี", "tired":"เหนื่อยนิดหน่อย", "pain":"มีอาการปวด", "minutes":"วันนี้วิ่งได้กี่นาที?", "goal":"เป้าหมายการวิ่งวันนี้คืออะไร?", "easy":"วิ่งเบา ๆ", "fitness":"เพิ่มความฟิต", "weight":"ควบคุมน้ำหนัก", "race":"เตรียมแข่ง", "submit":"รับโค้ชฟรีจากซุนกึม", "thinking":"ซุนกึมกำลังจัดแผนวันนี้…", "error":"สร้างแผนโค้ชไม่สำเร็จ", "plan":"แผนวันนี้", "intensity":"ระดับที่แนะนำ", "warmup":"วอร์มอัป", "caution":"ข้อควรระวัง", "cooldown":"คูลดาวน์", "feedback_title":"โค้ชวิ่งซุนกึมเป็นอย่างไรบ้าง? 🐶", "feedback_prompt":"บอกเราเพื่อช่วยทำแผนครั้งต่อไปให้ดีขึ้นนะ", "helpful":"👍 มีประโยชน์", "neutral":"🙂 ปานกลาง", "not_helpful":"🤔 ยังต้องปรับปรุง", "feedback_placeholder":"ฝากความคิดเห็นสั้น ๆ (ไม่บังคับ)", "feedback_send":"ส่งความคิดเห็น", "thanks":"ขอบคุณ! ครั้งหน้าจะช่วยได้ดียิ่งขึ้น 🐶✨", "fallback":"ใช้แผนโค้ชพื้นฐานที่ปลอดภัยให้แล้ว", "ai":"ซุนกึมจัดแผนให้เหมาะกับคุณแล้ว"
    },
    "zh": {
        "eyebrow":"顺金跑步教练", "title":"今天和顺金一起制定跑步计划吧？", "desc":"即使没有视频，也能根据今天的状态免费生成跑步计划。", "condition":"今天感觉怎么样？", "good":"很好，想轻松跑", "normal":"状态正常", "tired":"有点累", "pain":"有疼痛", "minutes":"今天能跑几分钟？", "goal":"今天的跑步目标是什么？", "easy":"轻松慢跑", "fitness":"提升体能", "weight":"体重管理", "race":"准备比赛", "submit":"领取顺金免费指导", "thinking":"顺金正在整理今天的计划…", "error":"无法生成指导计划。", "plan":"今日计划", "intensity":"推荐强度", "warmup":"热身", "caution":"注意事项", "cooldown":"放松", "feedback_title":"顺金跑步教练怎么样？ 🐶", "feedback_prompt":"告诉我一次，我会把下次计划做得更好。", "helpful":"👍 有帮助", "neutral":"🙂 一般", "not_helpful":"🤔 需要改进", "feedback_placeholder":"留下简短评价（可选）", "feedback_send":"发送评价", "thanks":"谢谢！下次我会帮得更好 🐶✨", "fallback":"已使用安全的基础指导计划。", "ai":"顺金已为你量身整理计划。"
    },
    "es": {
        "eyebrow":"Entrenador de running Sungeum", "title":"¿Planeamos la carrera de hoy juntos?", "desc":"Crea gratis un plan adaptado a cómo te sientes hoy, incluso sin vídeo.", "condition":"¿Cómo te sientes hoy?", "good":"Bien, quiero correr suave", "normal":"Me siento normal", "tired":"Estoy un poco cansado", "pain":"Tengo dolor", "minutes":"¿Cuántos minutos puedes correr hoy?", "goal":"¿Cuál es tu objetivo de hoy?", "easy":"Trote suave", "fitness":"Mejorar resistencia", "weight":"Controlar peso", "race":"Preparar una carrera", "submit":"Recibir coaching gratis", "thinking":"Sungeum está preparando tu plan…", "error":"No pudimos crear el plan.", "plan":"Plan de hoy", "intensity":"Intensidad recomendada", "warmup":"Calentamiento", "caution":"Precauciones", "cooldown":"Vuelta a la calma", "feedback_title":"¿Qué te pareció el coach de running? 🐶", "feedback_prompt":"Cuéntamelo una vez para mejorar tu próximo plan.", "helpful":"👍 Me ayudó", "neutral":"🙂 Normal", "not_helpful":"🤔 Puede mejorar", "feedback_placeholder":"Comentario breve (opcional)", "feedback_send":"Enviar opinión", "thanks":"¡Gracias! La próxima vez te ayudaré mejor 🐶✨", "fallback":"Usé un plan básico y seguro.", "ai":"Sungeum adaptó este plan para ti."
    }
}
